### PR TITLE
Adds and updates urdf ecosystem diagram

### PR DESCRIPTION
**Pull request by IanTheEngineer**
- Migrates urdf_diagram.odg and urdf_diagram.png from robot_model pkg
to this urdf pkg

- Updates urdf_diagram for current repo structures and urls

- Adds rendering from diagram in README.md

### CODE REVIEW

**Comment by IanTheEngineer** [comment]
@clalancette here are the updates based on our discussion yesterday

**Review by clalancette — APPROVED** [review]
This looks good to me, thanks for the update @IanTheEngineer

**Comment by clalancette** [comment]
@sloretz Any objection to merging these binary data files into this git repository?

**Review by sloretz — APPROVED** [review]

**Comment by IanTheEngineer** [comment]
@clalancette & @sloretz - I can't upload the new diagram to the ROS wiki (an admin is needed for image upload privileges i think?). Who should we ping to add the PR'd image to http://wiki.ros.org/urdf ?

**Comment by clalancette** [comment]
> @clalancette & @sloretz - I can't upload the new diagram to the ROS wiki (an admin is needed for image upload privileges i think?). Who should we ping to add the PR'd image to http://wiki.ros.org/urdf ?

I've uploaded it now.

**Pull request merged**
